### ISSUE TITLE
Codificación de la pagina web

### ISSUE THREAD

**Issue by NathalyBermeo97** [NathalyBermeo97/FDDS_PROYECTOFINAL#3]
Inicio de codificación de la pagina web con los lenguajes aprendidos.

**Comment by NathalyBermeo97** [comment]
- [ ] Formulario de registro.
- [ ] Formulario de inscripción de curso.
- [ ] Formulario de publicación de curso.
- [ ] Formulario de postulación de pasantías.
- [ ] Formulario de publicación de pasantías.
- [ ] Formulario de creación de eventos.

**Comment by NathalyBermeo97** [comment]
- [ ] Codificación de la navegación y del footer.
- [ ] Codificación de la pagina de inicio.
- [ ] Codificación de la pagina de eventos.
- [ ] Codificación de la pagina de cursos.
- [ ] Codificación de la pagina de pasantías.
- [ ] Codificación del perfil.
- [ ] Codificación de el calendario.
- [ ] Codificación de la agenda.

**Comment by NathalyBermeo97** [comment]
- [x] Formulario de registro.
- [x] Formulario de inscripción de curso.
- [x] Formulario de publicación de curso.
- [x] Formulario de postular pasantía.
- [x] Formulario de publicación de pasantía.
- [x] Formulario de creación de eventos.

**Comment by NathalyBermeo97** [comment]
- [x] Codificación de la pagina de inicio.
- [x] Codificación de la pagina de cursos.
- [x] Codificación de la pagina de eventos.
- [x] Codificación de la pagina de pasantías.
- [x] Codificación de la sección del perfil.
- [x] Codificación de la navegación y el footer.
- [x] Codificación del calendario.
- [x] Codificación de la agenda.

**Comment by NathalyBermeo97** [comment]
Codificación de el perfil.

- [x] Información personal.
- [x] Ver cursos.
- [x] Editar cursos.
